spring:
  application:
    name: SpringBootProject
  server:
    port: 8081
    servlet:
      context-path: /api

  datasource:
    url: jdbc:postgresql://localhost:5432/db?stringtype=unspecified&prepareThreshold=0&ApplicationName=${spring.application.name}
    username: test123
    password: test123
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 0
      maximum-pool-size: 20
      connection-timeout: 10000
      idle-timeout: 10000
      max-lifetime: 1800000
      auto-commit: false
      keepalive-time: 60000

  data:
    redis:
      host: localhost
      port: 6379
      # password: 123456
      min-idle: 1
      max-idle: 10
      max-total: 20
      max-wait-millis: 10000
      connect-timeout: 2000
      read-timeout: 2000
      nodes:
        - localhost

  jpa:
    open-in-view: false

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000

jwt:
  expiration: 7200000
  secret: 9f253cc5c66c4c4bbd1a6781068d5aea
